from .app import (
    APP_NAME,
    ENDPOINT_QC_LOG,
    FIREBASE_ERR_MSGS,
    GUEST_PASSWORD,
    GUEST_USER_NAME,
    KEY_USER_ID,
    KEY_USER_NAME,
)
from .colab_constants import PL_KEY_QC_COUNT, PL_KEY_USER_ID
from .db_keys import (
    COL_DESIRED_SKILLS_SETTINGS,
    COL_QC_LOGS,
    COL_QC_STATS,
    COL_USERNAME_MAP,
    COL_USERS,
    FIELD_ALERT_DAYS,
    FIELD_CREATED_AT_STR,
    FIELD_EMAIL,
    FIELD_EXECUTED_AT,
    FIELD_INPUT_ZIP_FILE,
    FIELD_IS_QC_LOG_PUBLIC,
    FIELD_MAP_EMAIL,
    FIELD_QC_COUNT,
    FIELD_QC_LAST_EXECUTED_AT,
    FIELD_QC_MONTHLY_COUNT,
    FIELD_SKILLS,
    FIELD_SKILLS_SETTINGS_NAME,
    FIELD_TOTAL_QC_COUNT,
    FIELD_USER_NAME,
    FIELD_YEAR_MONTH,
)
from .paths import BASE_DIR, OCR_NOTEBOOK_PATH
from .routes import (
    DEFAULT_PAGE_TITLE,
    DEFAULT_UI_TITLE,
    HOME,
    LOGIN,
    PAGE_TITLES,
    ROUTE_OCR,
    ROUTE_QC_LOG,
    ROUTE_SKILLS_SETTINGS,
    SETTINGS,
    UI_TITLES,
)
from .settings import DEFAULT_ALERT_DAYS, DEFAULT_IS_QC_LOG_PUBLIC
from .skills import SKILL_MASTER_LIST, SKILLS_DATA
from .urls import (
    ANDROID_UNCOMPRESSED_APP_DOWNLOAD_URL,
    GIST_URL,
    LATEST_BAT_DOWNLOAD_URL,
)
