from .app import (
    APP_NAME,
    KEY_USER_NAME,
    KEY_USER_ID,
    ENDPOINT_QC_LOG,
    GUEST_PASSWORD,
    GUEST_USER_NAME,
    FIREBASE_ERR_MSGS
)
from .colab_constants import (
    PL_KEY_USER_ID,
    PL_KEY_QC_COUNT
)
from .db_keys import (
    COL_USERS,
    COL_DESIRED_SKILLS_SETTINGS,
    COL_QC_LOGS,
    COL_QC_STATS,
    COL_USERNAME_MAP,
    FIELD_USER_NAME,
    FIELD_EMAIL,
    FIELD_SKILLS,
    FIELD_SKILLS_SETTINGS_NAME,
    FIELD_INPUT_ZIP_FILE,
    FIELD_EXECUTED_AT,
    FIELD_QC_COUNT,
    FIELD_CREATED_AT_STR,
    FIELD_IS_QC_LOG_PUBLIC,
    FIELD_ALERT_DAYS,
    FIELD_TOTAL_QC_COUNT,
    FIELD_YEAR_MONTH,
    FIELD_QC_MONTHLY_COUNT,
    FIELD_QC_LAST_EXECUTED_AT,
    FIELD_MAP_EMAIL
)
from .paths import (
    BASE_DIR,
    OCR_NOTEBOOK_PATH
)
from .routes import (
    LOGIN,
    ROUTE_OCR,
    ROUTE_SKILLS_SETTINGS,
    ROUTE_QC_LOG ,
    SETTINGS,
    HOME,
    PAGE_TITLES,
    UI_TITLES,
    DEFAULT_PAGE_TITLE,
    DEFAULT_UI_TITLE
)
from .settings import (
    DEFAULT_ALERT_DAYS,
    DEFAULT_IS_QC_LOG_PUBLIC
)
from .skills import (
    SKILL_MASTER_LIST,
    SKILLS_DATA
)
from .urls import GIST_URL