from .save_settings_dialog import SaveSettingsDialog
from .settings_edit_dialog import SettingsEditDialog
from .linked_sentence import LinkedSentence
from .settings_run_ocr_dialog import SettingsRunOCRDialog
from .detail_dialog import DetailDialog
from .sentences import get_open_colab_sentence